// demo/react/src/List/List.js
import { PureComponent } from 'react'
import JLSDK from '../sdk';
import enhanceUseNavigate from '../enhanceUseNavigate';

export class List extends PureComponent {
    constructor(props){
        super(props)
        this.state = {
            userId:'',
            groupList:[],
            groupId:'',
            deviceList:[],
            sn:'',
            adminToken:''
        }
    }

    onChangeSn(ev){
        this.setState({
            sn:ev.target.value
        })
    }
    onChangeAdminToken(ev){
        this.setState({
            adminToken:ev.target.value
        })
    }

    componentDidMount(){
        this.userinfo2()
        this.iotGetUserGroupListByPage()
    }

    userinfo2(){
        JLSDK.userinfo2().then(res => {
            const result = JSON.parse(decodeURIComponent(res.data || '{}'))
            let userId = result.data.userId
            this.setState({
                userId:userId
            })
        })
    }

    iotGetUserGroupListByPage(){
        let data = {
            page: 1,
            limit: 999
        }
        JLSDK.iotGetUserGroupListByPage(data).then(res => {
            let groupList = res && res.data && res.data.data && res.data.data.data || []
            this.setState({
                groupList:groupList
            })
        })
    }

    iotGetDeviceListByPage(){
        let data = {
            userGroupId:this.state.groupId,
            page: 1,
            limit: 999
        }
        JLSDK.iotGetDeviceListByPage(data).then(res => {
            let deviceList = res && res.data && res.data.data && res.data.data.data || []
            this.setState({
                deviceList:deviceList
            })
        })
    }

    onChange(ev){
        this.setState({
            groupId:ev.target.value
        },()=>{
            this.iotGetDeviceListByPage()
        })
    }

    onClick(item){
        this.setState({
            sn: item.deviceNo,
            adminToken: item.adminToken
        })
    }

    onSubmit(){
        JLSDK.setDevice({
            sn:this.state.sn,
            adminToken:this.state.adminToken
        })
        this.props.router.navigate('/info')
    }

    render(){
        return (
            <div id='app'>
                <div className="content">
                    <div style={{textAlign: 'center'}}>
                        <h3>Family</h3>
                        <select onChange={this.onChange.bind(this)}>
                        <option key='' value='' >select</option>
                            {
                                this.state.groupList.map(item => {
                                    return <option key={item.id} value={item.id} >{item.groupName} </option>
                                })
                            }
                        </select>
                    </div>
                    <div style={{clear:'both',overflow: 'hidden'}}>
                        {
                            this.state.deviceList.map(item => {
                                return <div className="item" key={item.deviceNo} onClick={this.onClick.bind(this,item)}>{ item.deviceName }</div>
                            })
                        }
                    </div>
                    
                    <form>
                        <h3>Get or customize device information</h3>
                        <label>
                            <span>sn</span>
                            <input type="text" defaultValue={this.state.sn} onChange={this.onChangeSn.bind(this)}/>
                        </label>
                        <label>
                            <span>adminToken</span>
                            <input type="text" defaultValue={this.state.adminToken} onChange={this.onChangeAdminToken.bind(this)}/>
                        </label>
                        <label>
                            <button type="button" onClick={this.onSubmit.bind(this)}>Device login</button>
                        </label>
                    </form>
                </div>
            </div>
        )
    }
}

export default enhanceUseNavigate(List)

// demo/uniapp/src/pages/list/list.vue
<template>
	<view id="app">
        <view style="text-align: center;">
            <h3>Family</h3>
            <select v-model="groupId" @change="onchange">
                <option value="">select</option>
                <option v-for="item in groupList" :key="item.id" :value="item.id" >{{ item.groupName }}</option>
            </select>
        </view>
        <view style="clear:both;overflow: hidden;">
            <view class="item" v-for="item in deviceList" :key="item.deviceNo" @click="onClick(item)">{{ item.deviceName }}</view>
        </view>
        
        <form>
            <h3>Get or customize device information</h3>
            <label>
                <span>sn</span>
                <input type="text" v-model="sn" />
            </label>
            <label>
                <span>adminToken</span>
                <input type="text" v-model="adminToken" />
            </label>
            <label>
                <button type="button" @click="onSubmit">Device login</button>
            </label>
        </form>
	</view>
</template>

<script>
	export default {
		data() {
			return {
                userId:'',
                groupList:[],
                groupId:'',
                deviceList:[],

                sn: '',
                adminToken:''
			}
		},
		onShow() {
            console.log('JLSDK',JLSDK);
            this.userinfo2()
            this.iotGetUserGroupListByPage()
		},
		methods: {
            userinfo2(){
                JLSDK.userinfo2().then(res => {
                    const result = JSON.parse(decodeURIComponent(res.data || '{}'))
                    this.userId = result.data.userId
                    console.log('userinfo2',result,this.userId)
                })
            },
            iotGetUserGroupListByPage(){
                let data = {
                    page: 1,
					limit: 999
                }
                JLSDK.iotGetUserGroupListByPage(data).then(res => {
                    this.groupList = res.data.data.data
                })
            },
            iotGetDeviceListByPage(){
                let data = {
                    userGroupId:this.groupId,
                    page: 1,
					limit: 999
                }
                JLSDK.iotGetDeviceListByPage(data).then(res => {
                    this.deviceList = res.data.data.data
                    console.log(this.deviceList);
                })
            },
            onchange(){
                this.iotGetDeviceListByPage()
                console.log('JLSDK',JLSDK);
            },
            onClick(item){
                this.sn = item.deviceNo
                this.adminToken = item.adminToken
            },
            onSubmit(){
                JLSDK.setDevice({
                    sn:this.sn,
                    adminToken:this.adminToken
                })
                uni.navigateTo({
                    url:'/pages/info/info'
                })
            }
		}
	}
</script>
